# Ubuntu 20.04 image with NVIDIA CUDA + OpenGL and ROS2 Foxy
FROM nvidia/cudagl:11.4.2-base-ubuntu20.04
SHELL ["/bin/bash", "-c"]

# Install basic apt packages
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
 build-essential curl gnupg2 locales lsb-release
RUN dpkg-reconfigure locales

# Install ROS2 Foxy
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
 -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
RUN apt-get update \
 && apt-get install -y --no-install-recommends ros-foxy-desktop
RUN apt-get install -y python3-colcon-common-extensions
RUN echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc
