# Base Image for TurtleBot3 Simulation
FROM ros:humble
SHELL ["/bin/bash", "-c"]

# Install basic apt packages
RUN apt-get update && apt-get install -y --no-install-recommends \
 git libcanberra-gtk-module libcanberra-gtk3-module libqt5svg5-dev \
 python3-pip python3-opencv python3-tk python3-pyqt5.qtwebengine

# Install additional Python modules
RUN pip3 install matplotlib transforms3d

# Install additional ROS packages
RUN apt-get update && apt-get install -y --no-install-recommends \
 ros-humble-cartographer \
 ros-humble-cartographer-ros \
 ros-humble-gazebo-ros \
 ros-humble-navigation2 \
 ros-humble-nav2-bringup \
 ros-humble-rmw-cyclonedds-cpp

# Create Colcon workspace with external dependencies
RUN mkdir -p /turtlebot3_ws/src
WORKDIR /turtlebot3_ws/src
COPY dependencies.repos ./
RUN vcs import < dependencies.repos

# Build the base Colcon workspace, handing any extra missed dependencies.
WORKDIR /turtlebot3_ws
RUN source /opt/ros/humble/setup.bash \
 && apt-get update -y \
 && rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y \
 && colcon build --symlink-install

# Remove display warnings
RUN mkdir /tmp/runtime-root
ENV XDG_RUNTIME_DIR "/tmp/runtime-root"
RUN chmod -R 0700 /tmp/runtime-root
ENV NO_AT_BRIDGE 1

# Set up the entrypoint
COPY ./docker/entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]
