# Overlay Development Image for TurtleBot3 Simulation
FROM turtlebot3_base:latest

# Create an overlay Colcon workspace
RUN mkdir -p /overlay_ws/src \
 && cd /overlay_ws
COPY ./tb3_autonomy/ /overlay_ws/src/tb3_autonomy/
COPY ./tb3_worlds/ /overlay_ws/src/tb3_worlds/
# RUN source /opt/ros/humble/setup.bash \
#  && source /turtlebot3_ws/install/setup.bash \
#  && cd /overlay_ws \
#  && colcon build

# Set up the work directory and entrypoint
WORKDIR /overlay_ws
COPY ./docker/entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]
